FROM fedora:40

RUN dnf install -y \
    cmake \
    gcc-c++ \
    pkgconfig \
    fltk-devel \
    mpv-devel \
    mpv \
    python3-pip \
    python3-pillow \
    rpm-build \
    wget \
    && dnf clean all

WORKDIR /app

COPY . .

RUN chmod +x scripts/build-rpm.sh && scripts/build-rpm.sh
